# Generated by Django 5.1.5 on 2025-04-21 20:54

import django.core.validators
import equipo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_equipos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), equipo.models.validate_image_size]),
        ),
    ]
