# Generated by Django 5.1.5 on 2025-04-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_remove_equipo_logo_url_equipo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
