# Generated by Django 5.1.7 on 2025-03-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('dueño', 'Dueño'), ('admin', 'Administrador'), ('entrenador', 'Entrenador')], max_length=10)),
                ('detalles', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
