# Generated by Django 5.1.5 on 2025-04-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
