# Generated by Django 5.1.6 on 2025-04-15 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDeporte',
            fields=[
                ('deporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='deporte.deporte')),
                ('max_titulares', models.IntegerField()),
                ('max_suplentes', models.IntegerField()),
            ],
        ),
    ]
