# Generated by Django 5.1.7 on 2025-03-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deporte.deporte')),
            ],
        ),
    ]
