# Generated by Django 5.1.6 on 2025-04-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dato', models.CharField(max_length=100)),
                ('tipo_movimiento', models.CharField(choices=[('INSERT', 'Inserción'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('OTHER', 'Otro')], max_length=10)),
                ('valores', models.JSONField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('host_origen', models.CharField(max_length=45)),
                ('usuario', models.CharField(max_length=45)),
            ],
        ),
    ]
