# Generated by Django 5.1.5 on 2025-04-21 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deporte', '0002_alter_deporte_nombre'),
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='deporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='deporte.deporte'),
        ),
        migrations.AddField(
            model_name='evento',
            name='puntos_equipo1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='puntos_equipo2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='resultado_equipo1',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='resultado',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
